### ISSUE TITLE
Error getting the card integrated

### ISSUE THREAD

**Issue by maas012** [LRvdLinden/UptimeRobot-HA-Card#1]
Getting a error can someone who add this to the HA share the code of the card

**Comment by LRvdLinden** [comment]
Hi @maas012 what for error do you get?

**Comment by maas012** [comment]
I'am new in HA try to get the card in place so question was how to add the sensor copy past it from you example but getting error. Don't kown if I have the sensor OK put the code below in the Conf.yaml

binary_sensor:
      - platform: uptimerobot
        api_key: u1268602-xxxxxxxxxx

and on the card the screen below

![image](https://user-images.githubusercontent.com/67659312/114441199-5f08a300-9bcb-11eb-83a7-2fde5706e075.png)

**Comment by LRvdLinden** [comment]
Plaats is Type: recht boven cards:?

**Comment by LRvdLinden** [comment]
and you're sensor is wrong. please try it this way:
    binary_sensor:
      - platform: uptimerobot
        api_key: YOUR_API_KEY

**Comment by maas012** [comment]
Some improved now line 10
![image](https://user-images.githubusercontent.com/67659312/114443194-b0199680-9bcd-11eb-87d0-f6686100a846.png)

conf.yaml was already OK
![image](https://user-images.githubusercontent.com/67659312/114443355-e1926200-9bcd-11eb-89f2-d287c26f84ac.png)

**Comment by LRvdLinden** [comment]
Okay in Dutch. Je hebt al je spaties verkeerd. zet type is boven cards. Daarnaast klopt je sensor qua spaties ook niet. Zet de letters onder elkaar zoals in het voorbeeld. Restart dan HA en alles doet het.

**Comment by maas012** [comment]
Heb hem nu zoals het voorbeeld maar blijft de error houden kan dan ook niet save doen

![image](https://user-images.githubusercontent.com/67659312/114449399-fb837300-9bd4-11eb-8cf1-988c3d551293.png)

**Comment by LRvdLinden** [comment]
Ik zie nog verkeerde spaties. Zie bij alias 

![image](https://user-images.githubusercontent.com/77990847/114449894-9da35b00-9bd5-11eb-890c-d55cfbc7bd7c.jpeg)

**Comment by maas012** [comment]
Top hij is nu OK thanks voor meedenken

**Comment by el97** [comment]
Hi! I need help with this as well. It would be nice to post a English guide to fix this.

**Comment by LRvdLinden** [comment]
Can you show me your card and sensor?
